version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: lanchonete-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - lanchonete-network

  payara:
    image: payara/server-full:6.2023.7
    container_name: lanchonete-payara
    environment:
      ADMIN_PASSWORD: ${PAYARA_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - ./dist/APS-04.war:/opt/payara/deployments/APS-04.war
    depends_on:
      - postgres
    networks:
      - lanchonete-network

networks:
  lanchonete-network:
    driver: bridge

volumes:
  postgres_data: